### ISSUE TITLE
The client is unable to access 5901 port

### ISSUE THREAD

**Issue by ximury** [LibVNC/x11vnc#177]
The client uses novnc to access the VNC server in the container. The server receives the request and opens the VNC service. However, the client cannot access port 5901 of the server. What is the reason? 

The version of x11vnc is 0.9.13

**Comment by pepperoni-pi** [comment]
Is the client trying to access x11vnc on port 5901 from the container? Or are you saying that it works to access the container, but not x11vnc from the client? What command are you running to launch x11vnc?

**Comment by ximury** [comment]
Run novnc in the container, and the client machine uses x11vnc command to run VNC service

**Comment by pepperoni-pi** [comment]
The novnc container would not be able to access the local loopback (127.0.0.1) of the server on port 5901. If you want to access it from the container you'd have to bind x11vnc to the IP of the server (i.e. 192.168.1.10) and use that to access it rather than 127.0.0.1. This will expose x11vnc to other devices on the network though.
